### PR TITLE
New settings

### PR DESCRIPTION
**Pull request by Ned-Tom**
Quick and dirty version whit settings.
Mentioned in : #94

**ToDo:**
- [x] Write new preferences page
- [x] Re implement G-settings
- [x] Setup translations
- [x] Cleanup

### CODE REVIEW

**Comment by Ned-Tom** [comment]
Closing this pull request because i would love to continue the project, but at the phase this project moves  its very hard for me to continue.

**Comment by Ned-Tom** [comment]
Closing this pull request because i would love to continue the project, but at the phase this project moves its very hard for me to continue.

**Comment by fthx** [comment]
Yep I understand, I don't have the time to manage this (and I do use Task Up extension rather than a dock, atm).
Feel free to fork.

**Comment by Ned-Tom** [comment]
Thanks @fthx, Good luck whit the "Task Up extension" and i will indeed continuity the fork.

**Pull request closed without merging**
