### PR TITLE
Use mouse wheel to change workspace

### PR DESCRIPTION
**Pull request by rastersoft**
Use mouse wheel to change workspace

This patch implements changing the current workspace by using the mouse wheel over the dock.

Fix https://github.com/fthx/dock-from-dash/issues/23

### CODE REVIEW

**Comment by rastersoft** [comment]
There is only one little problem with this: since the dock is about 16 pixels over the bottom of the screen, if you want to change the desktop you must go down to show the dock, and then move the mouse up to enter the dock. It would be better if the dock is completely at the bottom of the screen.

**Comment by fthx** [comment]
Your code is better than what I did. The scroll part is the same but your way of changing workspaces is nicer (I did that with indexes!).

**Comment by fthx** [comment]
I did not reply on one point: the dock position is exactly the same as its overview position. So when the dock is displayed and you enter overview (for whatever unknown reason), there are no visual glitches.

**Comment by rastersoft** [comment]
Yes, it was my mistake: the reason why the scroll didn't work at the bottom was due to the widget that you  use to detect when the mouse is there and show the dock. It was only a matter of connecting the scroll signal to it too.

**Comment by rastersoft** [comment]
BTW: now that this is implemented, what do you think about not hiding the dock after clicking on an icon to launch an app? Because I usually, at login, launch the mail client in the first workspace, switch to the next, launch firefox, switch to the next, and launch telegram, all in a row.

**Comment by fthx** [comment]
https://github.com/fthx/dock-from-dash/issues/26
to continue

**Pull request merged**
