### PR TITLE
Keep dock when app menu is shown

### PR DESCRIPTION
**Pull request by rastersoft**
When the user right-click on an icon, the dock must remain. This MR implements this.

Fix https://github.com/fthx/dock-from-dash/issues/28

### CODE REVIEW

**Comment by fthx** [comment]
What do you think of my way?
https://github.com/fthx/dock-from-dash/commit/9c40d62a7232678e2c73731c15e3a817cd31f0ac
It's working except if: right click, leave the popup menu without clicking on an item => the dock does not hide.

**Comment by rastersoft** [comment]
Mmm... do you really need to touch the prototype? Wouldn't it work just by replacing the method in the Dock class?

**Comment by fthx** [comment]
(I'm reworking some points.)
Could you tell me how to make these prototypes modifs to be clean?
There is another one in code: is there another way of modifying the app icon click?
Sorry, these points are not clear for me, that was the first time I did that.

**Comment by rastersoft** [comment]
I did some changes to my MR. Check it out.

**Comment by rastersoft** [comment]
I think that it is better to just have a centralized place where to decide it the mouse is hovering the dock or not.

**Comment by fthx** [comment]
What do you think of:
https://github.com/fthx/dock-from-dash/commit/fa21caf95e7cafc947e145ae53682333476b6014
?
This way makes the new code very short.
I'll look at your latest commits now.

**Comment by fthx** [comment]
Argh, you pointed out the second popup menu issue in your comment.
I'll look at this and if I don't find a correct and short way I'll push your code.

**Comment by fthx** [comment]
I had to remove the 'super' line because it does not work after resume from sleep.

**Pull request closed without merging**
